# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    # Runs at 12:00 AM every day (adjust as necessary)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v2

    # Generate the snake
    - uses: Platane/snk@v2
      id: snake-gif
      with:
        github_user_name: sayyam44
        # Output paths for GIF and SVG
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Show the status of the build for debugging purposes
    - run: git status

    # Push the changes to the main branch
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true

    # Push to GitHub Pages
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: main
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
