name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00 AM every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          # Generate the snake in a .svg file
          # Output is stored in the `output/snake.svg` file
          output: dist/snake.svg

      - name: Push the Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
